from __future__ import annotations

from ..llm.base import BaseLLM
from .retriever import Retriever

_CONTEXT_PROMPT = (
    "Here is a chunk from a larger document:\n\n"
    "<chunk>\n{chunk}\n</chunk>\n\n"
    "Please give a short (1-2 sentence) context that situates this chunk "
    "within the overall document. The context should help a search engine "
    "understand what this chunk is about. Return only the context, nothing else."
)


class ContextualRetriever:
    """Contextual Retrieval: prepend LLM-generated context to each chunk.

    Inspired by Anthropic's Contextual Retrieval approach. Before embedding,
    each chunk is enriched with a short context sentence generated by an LLM,
    improving retrieval accuracy for ambiguous or context-dependent chunks.

    Usage::

        cr = ContextualRetriever(retriever=retriever, llm=llm)
        await cr.add_with_context(["chunk1...", "chunk2..."])
        results = await cr.retrieve("query", top_k=5)
    """

    def __init__(
        self,
        retriever: Retriever,
        llm: BaseLLM,
        context_prompt: str | None = None,
    ) -> None:
        self._retriever = retriever
        self._llm = llm
        self._context_prompt = context_prompt or _CONTEXT_PROMPT

    async def _generate_context(self, chunk: str) -> str:
        """Generate a context sentence for a chunk."""
        prompt = self._context_prompt.format(chunk=chunk)
        return await self._llm.generate(prompt)

    async def add_with_context(
        self,
        texts: list[str],
        metadata: list[dict] | None = None,
    ) -> None:
        """Add texts to the retriever with LLM-generated context prepended."""
        enriched = []
        for text in texts:
            context = await self._generate_context(text)
            enriched.append(f"{context.strip()}\n\n{text}")

        await self._retriever.add(enriched, metadata)

    async def retrieve(
        self,
        query: str,
        top_k: int = 5,
        metadata_filter: dict | None = None,
    ) -> list[str]:
        """Retrieve using the enriched chunks."""
        return await self._retriever.retrieve(query, top_k=top_k, metadata_filter=metadata_filter)
